config:
  target: "http://localhost:3000"
  phases:
    - duration: 30 # total duration in seconds
      arrivalRate: 100 # number of users arriving per second
  processor: "./dataGenerator.js"
scenarios:
  # - name: "GET request for a single house info"
  #   weight: 80
  #   flow:
  #     - get:
  #         url: "/api/properties/{{$randomNumber(1, 10000000)}}"

  - name: "POST request to save a single house record"
    # weight: 20
    flow:
      - function: "generateRandomData"
      - post:
          url: "/post"
          followRedirect: true
          json: 
            _id: "{{ _id }}"
            zestimationPrice: "{{ zestimationPrice }}"
            startPriceRange: "{{ startPriceRange }}"
            endPriceRange: "{{ endPriceRange }}"
            thirtyDayPriceChange: "{{ thirtyDayPriceChange }}"
            oneYearForcast: "{{ oneYearForcast }}"
            propertyLastSalePrice: "{{ propertyLastSalePrice }}" 
            propertLastSaleDate: "{{ propertLastSaleDate }}"
            comparableHomePrice: "{{ comparableHomePrice }}"
            marketAppreciationPrice: "{{ marketAppreciationPrice }}"
            localSalesAvg: "{{ localSalesAvg }}"
            sellDate: "{{ sellDate }}" 
            sellPrice: "{{ sellPrice }}"
            beds: "{{ beds }}" 
            baths: "{{ baths }}"
            sqft: "{{ sqft }}" 
            streetAddress: "{{ streetAddress }}" 
            priceSqft: "{{ priceSqft }}"
            saleToList: "{{ saleToList }}"
            url: "{{ url }}"